<?php

function get_problem_open_options(){
	$options = &drupal_static(__FUNCTION__);
	if(!isset($options)){
		$options = array(
			'#options' => array(
	            'STUDENT&a=executionDemo' => t('Step through running the model'),
    	        'STUDENT&a=execution' => t('Run the model manually'),
        	    'COACHED&a=construction' => t('Reconstruct the model - Feedback on everything'),
            	'STUDENT&a=construction' => t('Reconstruct the model - Feedback on entries and graphs'),
	            'TEST&a=construction' => t('Reconstruct the model - Feedback on graphs only'),
    	        'EDITOR&a=construction' => t('Reconstruct the model - No feedback'),
        	    'AUTHOR&a=construction' => t('Edit the model'),
			),
			'#title' => t('Select a method to start Dragoon problem'),
			'#default_value' => 'COACHED&a=construction'
        );
	}

	return $options;
}
