<?php

/**
* The idea for resource bundles is to create static functions in drupal and call them
* from the piece of code that that will handle it.
* https://api.drupal.org/api/drupal/includes%21bootstrap.inc/function/drupal_static/7.x
* To understand drupal_static
*
* For Javascript these values will have to be added to the DOM structures and picked in JS.
* I have tested it, and it works fine. It was dummy code and I am not committing that
* ~ Sachin
**/
function get_problem_open_options(){
	$options = &drupal_static(__FUNCTION__);
	if(!isset($options)){
		$options = array(
			'#options' => array(
				'STUDENT&a=executionDemo' => t('Step through running the model'),
				'STUDENT&a=execution' => t('Run the model manually'),
				'COACHED&a=construction' => t('Reconstruct the model - Feedback on everything'),
				'STUDENT&a=construction' => t('Reconstruct the model - Feedback on entries and graphs'),
				'TEST&a=construction' => t('Reconstruct the model - Feedback on graphs only'),
				'EDITOR&a=construction' => t('Reconstruct the model - No feedback'),
				'AUTHOR&a=construction' => t('Edit the model'),
			),
			'#title' => t('Select a method to start Dragoon problem'),
			'#default_value' => 'COACHED&a=construction'
		);
	}

	return $options;
}

function get_create_assignment_options(){
	$options = &drupal_static(__FUNCTION__);
	if(!isset($options)){
		$options = array(
			'#options' => array(
				'STUDENT|executionDemo' => t('Step through running the model'),
				'STUDENT|execution' => t('Run the model manually'),
				'COACHED|construction' => t('Reconstruct the model - Feedback on everything'),
				'STUDENT|construction' => t('Reconstruct the model - Feedback on entries and graphs'),
				'TEST|construction' => t('Reconstruct the model - Feedback on graphs only'),
				'EDITOR|construction' => t('Reconstruct the model - No feedback'),
				'AUTHOR|construction' => t('Edit the model'),
			),
			'#title' => t('Select a method to start Dragoon problem'),
			'#default_value' => 'AUTHOR|construction'
		);
	}

	return $options;
}

function has_system_descriptions(){
	return false;
}

function get_tutor_name(){
	return "dragoon";
}

