<?php

function system_descriptions_form_alter(&$form, &$form_state, $form_id){
	switch($form_id){ 
		case "problem_form": //adds the system description button with weight -5 so that it appears just after the
			$form['sys-desc-inp'] = array(
				'#type' => 'button',
				'#value' => 'System descriptions',
				'#id' => 'open_sysdescmodal',
				'#display' => 'none',
				'#weight' => '-5'
			); 
			$form['#attached']['js'] = array(
				drupal_get_path('module', 'system_descriptions') . '/static/sys_desc.js',
			);
			break;
		}

	}

/* creates additional blocks which are specific to topomath in context of system descriptions*/

function createSpecificBlocks(){
	$specific_blocks = '<div id="confirmRemoveSysDesc" class="modal fade" role="dialog">
								<div class="modal-dialog">
								<!-- Modal content-->
									<div class="modal-content">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal">&times;</button>
												<h4 class="modal-title">Confirm Delete System Description</h4>
											</div>
										<div class="modal-body">
											<p>Are you sure you want to delete?</p>
										</div>
										<div class="modal-footer">
											<button type="button" class="btn btn-default" data-dismiss="modal" id="removeSysDescConfirmed">Yes! Delete</button>
											<button type="button" class="btn btn-default" data-dismiss="modal" data-toggle="modal">Cancel</button>
										</div>
									</div>
								</div>
							</div>';
	return $specific_blocks;
}

/*this function hosts additional copy/move functionality from common site */
function copyMoveExtension($src, $dest, $action){
	if($action == "moveModel"){
		//move the system descriptions to new table( simply update the folder name)
		return updateFolder($src, $dest);
	}
	else if($action == "copyModel"){
		//copy the system descriptions to new folder
		$row_details = db_select('system_descriptions','sh')->fields('sh',array('sd_name','sd_uname','sd_pname','sd_path','sd_section','sd_type'))->condition('sd_folder',$src)->execute();
		while($sys_desc_each = $row_details->fetchAssoc()){
			$query = db_insert('system_descriptions')->
					fields(array(
						"sd_name" => $sys_desc_each["sd_name"],
						"sd_uname" => $sys_desc_each["sd_uname"],
						"sd_pname" => $sys_desc_each["sd_pname"],
						"sd_path" => $sys_desc_each["sd_path"],
						"sd_folder" => $dest,
						"sd_section" => $sys_desc_each["sd_section"],
						"sd_type" => $sys_desc_each["sd_type"]
						))-> execute();
		}
	}
}

/*this function hosts additional rename functionality from common site */

function renameExtension($src, $dest){
	//In the renameExtension function in topomath, in the context of system descriptions
	//if a folder is renamed it has to be reflected in system descriptions table
	return updateFolder($src, $dest);
}

/* updateFolder functions updates the folder name in system_descriptions table
*/
function updateFolder($old, $new){

		$query =  db_update('system_descriptions')
					->fields(array(
						'sd_folder' => $new,
					))
					->condition('sd_folder',$old)
					->execute();
		if($query)
			return true;
}

/* Adding two separate blocks to host add new system descriptions and edit system descriptions forms*/
	
function system_descriptions_block_info(){
	$blocks = array();
	$blocks['new_system_descriptions'] = array(
		'info' => 'Block for adding new description'
	);
	$blocks['edit_system_descriptions'] = array(
		'info' => 'Block for editing system descriptions',
	);
	$blocks[''] = array(
		'info' => 'Block for '
	);
	return $blocks;
}

function system_descriptions_block_view($delta = ""){
	$block = array();
	$has_msg = isset($_REQUEST['msg'])?true:false;
	if($has_msg){
		$msg = $_REQUEST['msg'];
		switch ($delta) {
			case "new_system_descriptions":
				if($msg == "added")
					$block['content'] = "System description has been added succesfully";
			break;
			
			case "edit_system_descriptions":
				if($msg == "edited")
					$block['content'] = "System description has been updated succesfully";
				break;
		}

		return $block;
	}

	$edit_desc = isset($_REQUEST['edit'])?true:false;
	drupal_add_js(drupal_get_path('module', 'system_descriptions').'/cke/ckeditor/ckeditor.js', array('weight' => 100) );
	drupal_add_js(drupal_get_path('module', 'system_descriptions').'/cke/ckeditor/adapters/jquery.js', array('weight' => 200));
	drupal_add_js(drupal_get_path('module', 'system_descriptions').'/cke/manage_ck.js', array('weight' => 300));
	
	switch ($delta){
		case "new_system_descriptions":
			
			if(!$edit_desc){
				module_load_include('inc', 'system_descriptions', 'system_descriptions_new_desc_form');
				$form = drupal_get_form('system_descriptions_new_desc_form');
				$block['content'] = array(
					'#markup' => drupal_render($form),
				);
			}
			break;
		case "edit_system_descriptions":
			if($edit_desc){
				module_load_include('inc', 'system_descriptions', 'system_descriptions_edit_desc_form');
				$form = drupal_get_form('system_descriptions_edit_desc_form');
				$block['content'] = array(
					'#markup' => drupal_render($form),
				);
			}
			break;
	}

	return $block;
}
			

